/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoader: typeof import('./../.mono/apps/mono-host/app/components/AppLoader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedLayoutLogoutModal: typeof import('./../.mono/apps/mono-host/src/components/Shared/Layout/LogoutModal.vue')['default']
    SharedLayoutProfileDropdown: typeof import('./../.mono/apps/mono-host/src/components/Shared/Layout/ProfileDropdown.vue')['default']
    SharedLayoutSidebar: typeof import('./../.mono/apps/mono-host/src/components/Shared/Layout/Sidebar.vue')['default']
    SharedLayoutTopbar: typeof import('./../.mono/apps/mono-host/src/components/Shared/Layout/Topbar.vue')['default']
    UtilsCookieExp: typeof import('./../.mono/apps/mono-host/src/components/Utils/CookieExp.vue')['default']
    'UtilsCookieExp.client': typeof import('./../.mono/apps/mono-host/app/components/Utils/CookieExp.client.vue')['default']
  }
}
