/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SharedLayoutLogoutModal: typeof import('./components/Shared/Layout/LogoutModal.vue')['default']
    SharedLayoutProfileDropdown: typeof import('./components/Shared/Layout/ProfileDropdown.vue')['default']
    SharedLayoutSidebar: typeof import('./components/Shared/Layout/Sidebar.vue')['default']
    SharedLayoutTopbar: typeof import('./components/Shared/Layout/Topbar.vue')['default']
    UtilsCookieExp: typeof import('./components/Utils/CookieExp.vue')['default']
  }
}
